import SparseSGD.Discrete.StableKernel
import SparseSGD.Discrete.RenewalBounds
import SparseSGD.Discrete.Positivity

namespace SparseSGD

noncomputable section

/-- The risk generated by the deterministic mean dynamics. -/
def freeRisk (p : Params) (s : Moments) (k : ℕ) : ℝ :=
  ((p.meanMatrix ^ k) * s.cov * (p.meanMatrix ^ k).transpose) 0 0

theorem normalized_trajectory_recurrence (_jury : External.JuryStability)
    (p : Params) (s : Moments)
    (hb0 : 1 / 2 ≤ p.beta) (hb1 : p.beta < 1)
    (hw0 : 0 < p.w) (hw1 : p.w < 2 * (1 + p.beta))
    (k : ℕ) :
    (p.trajectory s k).R = freeRisk p s k +
      ∑ j ∈ Finset.range k,
        normalizedKernelLag p (k - j) *
          (p.renormNoise * (p.trajectory s j).R + p.renormAdditive) := by
  have hc : 0 < 1 - p.curvature := by
    unfold Params.curvature
    rw [sub_pos]
    apply (div_lt_iff₀ (by linarith : 0 < 2 * (1 + p.beta))).2
    linarith
  have hrec := Params.trajectory_R_renewal p s k
  rw [hrec]
  unfold freeRisk
  congr 1
  apply Finset.sum_congr rfl
  intro j hj
  have hjk : j < k := Finset.mem_range.mp hj
  have hage : k - j = (k - j - 1) + 1 := by omega
  have hresp : k - 1 - j = k - j - 1 := by omega
  rw [hage]
  simp only [normalizedKernelLag]
  rw [hresp]
  unfold Params.renormNoise Params.renormAdditive
  field_simp [ne_of_gt hc]

theorem normalized_kernel_partial_mass_le_one (jury : External.JuryStability)
    (p : Params) (hb0 : 1 / 2 ≤ p.beta) (hb1 : p.beta < 1)
    (hw0 : 0 < p.w) (hw1 : p.w < 2 * (1 + p.beta)) (k : ℕ) :
    (∑ n ∈ Finset.range k, normalizedKernelLag p (k - n)) ≤ 1 := by
  have hnonneg := normalized_kernel_lag_nonneg jury p hb0 hb1 hw0 hw1
  have hsum := normalized_kernel_lag_hasSum jury p hb0 hb1 hw0 hw1
  have hreflect :
      (∑ n ∈ Finset.range k, normalizedKernelLag p (k - n)) =
        ∑ n ∈ Finset.range k, normalizedKernelLag p (n + 1) := by
    calc
      (∑ n ∈ Finset.range k, normalizedKernelLag p (k - n)) =
          ∑ n ∈ Finset.range k, normalizedKernelLag p ((k - 1 - n) + 1) := by
            apply Finset.sum_congr rfl
            intro n hn
            have hnk : n < k := Finset.mem_range.mp hn
            congr 1
            omega
      _ = ∑ n ∈ Finset.range k, normalizedKernelLag p (n + 1) := by
            exact Finset.sum_range_reflect (fun n => normalizedKernelLag p (n + 1)) k
  have hzero : normalizedKernelLag p 0 = 0 := by simp [normalizedKernelLag]
  have hshift : (∑ n ∈ Finset.range k, normalizedKernelLag p (n + 1)) =
      ∑ n ∈ Finset.range (k + 1), normalizedKernelLag p n := by
    rw [Finset.sum_range_succ']
    simp [hzero]
  rw [hreflect, hshift]
  exact sum_le_hasSum (Finset.range (k + 1)) (fun n _ => hnonneg n) hsum

theorem trajectory_risk_uniform_bound (jury : External.JuryStability)
    (p : Params) (s : Moments) (A : ℝ)
    (hb0 : 1 / 2 ≤ p.beta) (hb1 : p.beta < 1)
    (hw0 : 0 < p.w) (hw1 : p.w < 2 * (1 + p.beta))
    (hnoise : 0 ≤ p.noise) (hadd : 0 ≤ p.additive)
    (hload : p.renormNoise < 1) (hA : 0 ≤ A)
    (hfree : ∀ k, freeRisk p s k ≤ A) :
    ∀ k, (p.trajectory s k).R ≤ (A + p.renormAdditive) / (1 - p.renormNoise) := by
  have hc : 0 < 1 - p.curvature := by
    unfold Params.curvature
    rw [sub_pos]
    apply (div_lt_iff₀ (by linarith : 0 < 2 * (1 + p.beta))).2
    linarith
  have hu0 : 0 ≤ p.renormNoise := by
    unfold Params.renormNoise
    positivity
  have hphi : 0 ≤ p.renormAdditive := by
    unfold Params.renormAdditive
    positivity
  apply scalar_renewal_bound (normalizedKernelLag p)
    (fun k => freeRisk p s k) (fun k => (p.trajectory s k).R)
    p.renormNoise p.renormAdditive A
  · exact normalized_kernel_lag_nonneg jury p hb0 hb1 hw0 hw1
  · exact normalized_kernel_partial_mass_le_one jury p hb0 hb1 hw0 hw1
  · exact hu0
  · exact hload
  · exact hphi
  · exact hA
  · exact hfree
  · exact normalized_trajectory_recurrence jury p s hb0 hb1 hw0 hw1

/-- The noise-generated excess over the free dynamics is nonnegative and uniformly bounded. -/
theorem trajectory_risk_defect_bound (jury : External.JuryStability)
    (p : Params) (s : Moments) (A : ℝ) (hs : s.psd)
    (hb0 : 1 / 2 ≤ p.beta) (hb1 : p.beta < 1)
    (hw0 : 0 < p.w) (hw1 : p.w < 2 * (1 + p.beta))
    (hnoise : 0 ≤ p.noise) (hadd : 0 ≤ p.additive)
    (hload : p.renormNoise < 1) (hA : 0 ≤ A)
    (hfree : ∀ k, freeRisk p s k ≤ A) :
    ∀ k, 0 ≤ (p.trajectory s k).R - freeRisk p s k ∧
      (p.trajectory s k).R - freeRisk p s k ≤
        (p.renormNoise * A + p.renormAdditive) / (1 - p.renormNoise) := by
  have hc : 0 < 1 - p.curvature := by
    unfold Params.curvature
    rw [sub_pos]
    apply (div_lt_iff₀ (by linarith : 0 < 2 * (1 + p.beta))).2
    linarith
  have hu0 : 0 ≤ p.renormNoise := by
    unfold Params.renormNoise
    positivity
  have hphi : 0 ≤ p.renormAdditive := by
    unfold Params.renormAdditive
    positivity
  have heps : 0 ≤ p.eps := by
    unfold Params.eps
    linarith
  have hnonneg := normalized_kernel_lag_nonneg jury p hb0 hb1 hw0 hw1
  have hmass := normalized_kernel_partial_mass_le_one jury p hb0 hb1 hw0 hw1
  have hR := trajectory_risk_uniform_bound jury p s A hb0 hb1 hw0 hw1
    hnoise hadd hload hA hfree
  let M : ℝ := (A + p.renormAdditive) / (1 - p.renormNoise)
  have hM : 0 ≤ M := by
    dsimp [M]
    positivity
  have hconstant : 0 ≤ p.renormNoise * M + p.renormAdditive := by positivity
  have hvalue : p.renormNoise * M + p.renormAdditive =
      (p.renormNoise * A + p.renormAdditive) / (1 - p.renormNoise) := by
    have hden : 1 - p.renormNoise ≠ 0 := by linarith
    dsimp [M]
    field_simp [hden]
    ring
  intro k
  have hdefect : (p.trajectory s k).R - freeRisk p s k =
      ∑ j ∈ Finset.range k, normalizedKernelLag p (k - j) *
        (p.renormNoise * (p.trajectory s j).R + p.renormAdditive) := by
    have hrec := normalized_trajectory_recurrence jury p s hb0 hb1 hw0 hw1 k
    linarith
  rw [hdefect]
  constructor
  · apply Finset.sum_nonneg
    intro j _
    have hjR : 0 ≤ (p.trajectory s j).R :=
      Moments.psd_R_nonneg (p.trajectory_psd s hs hw0.le heps hnoise hadd j)
    exact mul_nonneg (hnonneg (k - j)) (add_nonneg (mul_nonneg hu0 hjR) hphi)
  · calc
      (∑ j ∈ Finset.range k, normalizedKernelLag p (k - j) *
          (p.renormNoise * (p.trajectory s j).R + p.renormAdditive)) ≤
          ∑ j ∈ Finset.range k, normalizedKernelLag p (k - j) *
            (p.renormNoise * M + p.renormAdditive) := by
              apply Finset.sum_le_sum
              intro j _
              apply mul_le_mul_of_nonneg_left _ (hnonneg (k - j))
              exact add_le_add (mul_le_mul_of_nonneg_left (hR j) hu0) le_rfl
      _ = (p.renormNoise * M + p.renormAdditive) *
          (∑ j ∈ Finset.range k, normalizedKernelLag p (k - j)) := by
            rw [← Finset.sum_mul]
            ring
      _ ≤ (p.renormNoise * M + p.renormAdditive) * 1 :=
        mul_le_mul_of_nonneg_left (hmass k) hconstant
      _ = (p.renormNoise * A + p.renormAdditive) / (1 - p.renormNoise) := by
        simpa only [mul_one] using hvalue

end
end SparseSGD
